### ISSUE TITLE
QIF import makes every new account a Checking account

### ISSUE THREAD

**Issue by jeffjl74** [anselmh/CONTRIBUTING.md#5]
MMEX version 1.2.0-Beta.

My Quicken exported QIF file has the account type as part of the !Account record but MMEX QIF import is hard coded to create every new account as a Checking account.  Then MMEX does not allow "reallocating" a "Bank" account to a "Stock" account so my imported investment accounts are not properly categorized.

**Comment by anselmh** [comment]
Definitely does not belong to this repository.
