### ISSUE TITLE
Update pull request resources in CONTRIBUTING.md

### ISSUE THREAD

**Issue by whimatthew** [anselmh/CONTRIBUTING.md#7]
"GitHub pull request documentation" under "Additional Resources" dead links to http://help.github.com/send-pull-requests/. The closest live equivalent I find in GitHub help is https://help.github.com/articles/about-pull-requests/

Not actually dead, but moved, is the  "[`hub pull-request` command](https://github.com/defunkt/hub#git-pull-request)" documentation. The hub docs now seem to live at https://hub.github.com/hub.1.html

**Comment by anselmh** [comment]
Hey, thanks. Mind opening a pull request with these changes?

**Comment by whimatthew** [comment]
Sure thing.
